apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240113190927.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240113190927.0.0+build.02e9424
  releaseNotes: |
    Release v20240113190927.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-13-01-2024-13-35-19-967848051/where-for-dinner-ui-my-apps-bundle@sha256:dc6dbd43eb1d5e3a1838ba4ff0c6b20eb09e51dccf689f7ec0aad67c66122a84
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

